library(jsonlite)
transfer24 <- as.data.frame(fromJSON('https://barttorvik.com/2024_transfer_stats.json'))
transfer23 <- as.data.frame(fromJSON('https://barttorvik.com/2023_transfer_stats.json'))
transfer22 <- as.data.frame(fromJSON('https://barttorvik.com/2022_transfer_stats.json'))
transfer21 <- as.data.frame(fromJSON('https://barttorvik.com/2021_transfer_stats.json'))
transfer20 <- as.data.frame(fromJSON('https://barttorvik.com/2020_transfer_stats.json'))
write.csv(transfer24,'/Users/mileskee7/Desktop/College/Senior Year/W/course-paper-or-presentation-mileskee/transfer24.csv')
write.csv(transfer23,'/Users/mileskee7/Desktop/College/Senior Year/W/course-paper-or-presentation-mileskee/transfer23.csv')
write.csv(transfer22,'/Users/mileskee7/Desktop/College/Senior Year/W/course-paper-or-presentation-mileskee/transfer22.csv')
write.csv(transfer21,'/Users/mileskee7/Desktop/College/Senior Year/W/course-paper-or-presentation-mileskee/transfer21.csv')
write.csv(transfer20,'/Users/mileskee7/Desktop/College/Senior Year/W/course-paper-or-presentation-mileskee/transfer20.csv')
